Description: This template deployed QA env with new vpc as template and ASP.NET mvc sample application with Elastic Beanstalk in qa folder

Parameters:

  TemplateBucket:
    Type: String
    Default: aspnetmvc-cfn
    Description: The EB template bucket for the CloudFormation templates

  ApplicationName:
    Description: Name of your application
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"

  IsExistApplication:
    Description: Does your application exist?
    Default: true
    Type: String
    AllowedValues: 
      - true
      - false

  EnvironmentName:
    Type: String
    Description: Environment name - QA or DEV
    Default: QA
    AllowedValues:
      - QA
      - UAT
    ConstraintDescription: Specify either dev or prod

  # SSHFrom:
  #   Description: Limit SSH access to bastion hosts to a CIDR IP block
  #   Type: String
  #   MinLength: 9
  #   MaxLength: 18
  #   Default: 0.0.0.0/0

  ELBIngressPort:
    Description: The ELB ingress port used by security groups
    Type: Number
    MinValue: 0
    MaxValue: 65535
    ConstraintDescription: TCP ports must be between 0 - 65535
    Default: 80

  AppIngressPort:
    Description: The application ingress port used by security groups
    Type: Number
    MinValue: 0
    MaxValue: 65535
    ConstraintDescription: TCP ports must be between 0 - 65535
    Default: 80

  # # bastion.cfn.yml parameters
  # KeyName:
  #   Description: EC2 key pair name for bastion host SSH access
  #   Type: AWS::EC2::KeyPair::KeyName

  # LogRetentionInDays:
  #   Description: Number of days you would like your CloudWatch Logs to be retained
  #   Type: Number
  #   Default: 90

  # AppS3Bucket:
  #   Description: S3 Bucket containing your application package
  #   Type: String
  #   MinLength: 1
  #   MaxLength: 255

  # AppS3Key:
  #   Description: S3 Bucket key for your application package
  #   Type: String
  #   MinLength: 1
  #   MaxLength: 255

  # EbInstanceType:
  #   Description: The instance type for Elastic Beanstalk
  #   Type: String
  #   Default: t2.small
  #   ConstraintDescription: Instance type not supported
  #   AllowedValues:
  #     - t2.small
  #     - t2.medium
  #     - t2.large
  #     - t2.xlarge
  #     - t2.2xlarge
  #     - m5.large
  #     - m5.xlarge
  #     - m5.2xlarge
  #     - m5.4xlarge
  #     - m5.12xlarge
  #     - m5.24xlarge
  #     - r4.large
  #     - r4.xlarge
  #     - r4.2xlarge
  #     - r4.4xlarge
  #     - r4.8xlarge
  #     - r4.16xlarge

  AutoScalingMinInstanceCount:
    Description: Minimum number of EC2 instances for Auto Scaling
    Type: Number
    MinValue: 1
    MaxValue: 4
    Default: 2
    ConstraintDescription: Specify a number between 1 - 20

  AutoScalingMaxInstanceCount:
    Description: Maximum number of EC2 instances for Auto Scaling
    Type: Number
    MinValue: 1
    MaxValue: 4
    Default: 4
    ConstraintDescription: Specify a number between 1 - 20
  
  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 192.168.0.0/17
  
  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 192.168.1.0/26

  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: 192.168.1.64/26
  
  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 192.168.0.0/26

  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 192.168.0.64/26

  PrivateSubnet3CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the third Availability Zone
    Type: String
    Default: 192.168.0.128/26

  PrivateSubnet4CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the fourth Availability Zone
    Type: String
    Default: 192.168.0.192/26

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment
        Parameters:
          - EnvironmentName
      - Label:
          default: Application Global
        Parameters:
          - AppIngressPort
      - Label:
          default: Elastic Beanstalk
        Parameters:
          - ApplicationName
          - IsExistApplication
          - AutoScalingMinInstanceCount
          - AutoScalingMaxInstanceCount
      - Label:
          default: Load Balancer
        Parameters:
          - ELBIngressPort
      - Label:
          default: VPC
        Parameters:
          - VpcCIDR
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR
          - PrivateSubnet3CIDR
          - PrivateSubnet4CIDR
    
    ParameterLabels:
      ELBIngressPort:
        default: Port
      AppIngressPort:
        default: Port
      TemplateBucket:
        default: CloudFormation Bucket
      ApplicationName:
        default: Application Name
      IsExistApplication:
        default: Does Application Name exist?
      EnvironmentName:
        default: Environment Name
      AutoScalingMinInstanceCount:
        default: Min Instances
      AutoScalingMaxInstanceCount:
        default: Max Instances
      VpcCIDR:
        default: VPC CIDR
      PublicSubnet1CIDR:
        default: Public Subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public Subnet 2 CIDR
      PrivateSubnet1CIDR:
        default: Private Subnet 1 CIDR
      PrivateSubnet2CIDR:
        default: Private Subnet 2 CIDR
      PrivateSubnet3CIDR:
        default: Private Subnet 3 CIDR
      PrivateSubnet4CIDR:
        default: Private Subnet 4 CIDR

Resources:

  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/qa/vpc_cloudformation_qa_private_template.yml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ELBIngressPort: !Ref ELBIngressPort
        AppIngressPort: !Ref AppIngressPort
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        PrivateSubnet3CIDR: !Ref PrivateSubnet3CIDR
        PrivateSubnet4CIDR: !Ref PrivateSubnet4CIDR

  ElasticBeanstalkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/qa/eb_cloudformation_qa_private_template.yml
      Parameters:
        ApplicationName: !Ref ApplicationName
        IsExistApplication: !Ref IsExistApplication
        EnvironmentName: !Ref EnvironmentName
        NetworkStackName: !GetAtt VpcStack.Outputs.Name
        AutoScalingMinInstanceCount: !Ref AutoScalingMinInstanceCount
        AutoScalingMaxInstanceCount: !Ref AutoScalingMaxInstanceCount


Outputs:

  VpcStackName:
    Value: !GetAtt VpcStack.Outputs.Name
    Export:
      Name: !Sub ${AWS::StackName}-VpcStackName

  ElasticBeanstalkStackName:
    Value: !GetAtt ElasticBeanstalkStack.Outputs.Name
    Export:
      Name: !Sub ${AWS::StackName}-ElasticBeanstalkStack

